using Microsoft.EntityFrameworkCore;
using Enxoval.Web.Data;
using Enxoval.Web.Models;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllersWithViews();

var databaseUrl = Environment.GetEnvironmentVariable("DATABASE_URL");
if (!string.IsNullOrEmpty(databaseUrl))
{
    var uri = new Uri(databaseUrl);
    var userInfo = uri.UserInfo.Split(':');
    var endpointId = uri.Host.Split('.')[0];
    var builder_ = new Npgsql.NpgsqlConnectionStringBuilder
    {
        Host = uri.Host,
        Database = uri.AbsolutePath.TrimStart('/'),
        Username = userInfo[0],
        Password = userInfo[1],
        SslMode = Npgsql.SslMode.Require
    };
    if (uri.Port > 0) builder_.Port = uri.Port;
    var connString = builder_.ConnectionString + $";Options=endpoint={endpointId}";

    builder.Services.AddDbContext<AppDbContext>(o =>
        o.UseNpgsql(connString));
}
else
{
    builder.Services.AddDbContext<AppDbContext>(o =>
        o.UseSqlite("Data Source=enxoval.db"));
}

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    db.Database.EnsureCreated();

    db.Database.ExecuteSqlRaw("""
        CREATE TABLE IF NOT EXISTS "Categorias" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "Nome" text NOT NULL,
            "Ordem" integer NOT NULL,
            CONSTRAINT "PK_Categorias" PRIMARY KEY ("Id")
        );
        ALTER TABLE "Desejos" ADD COLUMN IF NOT EXISTS "CategoriaId" integer NULL;
    """);

    if (!db.Categorias.Any())
    {
        db.Categorias.AddRange(
            new Categoria { Nome = "Cozinha", Ordem = 1 },
            new Categoria { Nome = "Sala de Estar", Ordem = 2 },
            new Categoria { Nome = "Quarto", Ordem = 3 },
            new Categoria { Nome = "Banheiro", Ordem = 4 },
            new Categoria { Nome = "Eletrodomésticos", Ordem = 5 },
            new Categoria { Nome = "Decoração", Ordem = 6 }
        );
        db.SaveChanges();
    }
}

app.UseStaticFiles();
app.UseRouting();
app.MapControllerRoute("default", "{controller=Home}/{action=Index}/{id?}");

app.Run();
