CREATE TABLE IF NOT EXISTS casal (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome1 VARCHAR(100) NOT NULL,
  nome2 VARCHAR(100) NOT NULL,
  data_casamento DATE DEFAULT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  slug VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS categorias (
  id INT AUTO_INCREMENT PRIMARY KEY,
  casal_id INT NOT NULL,
  nome VARCHAR(100) NOT NULL,
  ordem INT DEFAULT 0,
  FOREIGN KEY (casal_id) REFERENCES casal(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS itens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  casal_id INT NOT NULL,
  categoria_id INT DEFAULT NULL,
  nome VARCHAR(200) NOT NULL,
  descricao TEXT,
  preco DECIMAL(10,2) DEFAULT 0,
  imagem VARCHAR(500) DEFAULT '',
  loja VARCHAR(200) DEFAULT '',
  url VARCHAR(500) DEFAULT '',
  ordem INT DEFAULT 0,
  FOREIGN KEY (casal_id) REFERENCES casal(id) ON DELETE CASCADE,
  FOREIGN KEY (categoria_id) REFERENCES categorias(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reservas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  item_id INT NOT NULL,
  convidado_nome VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (item_id) REFERENCES itens(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
